name: CD to Vercel on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout del código
    - name: Check out code
      uses: actions/checkout@v3

    # Configurar Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'npm'

    # Instalar dependencias
    - name: Install dependencies
      run: npm install

    # Construir el proyecto
    - name: Build Vite project
      run: npm run build

    # Desplegar a Vercel
    - name: Deploy to Vercel (Preview)
      run: npx vercel --token=$VERCEL_TOKEN --scope=$SCOP_NAME --prod-if-unlocked=false
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
