name: CI for Vite Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout del código
    - name: Check out code
      uses: actions/checkout@v3

    # Configurar Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'npm'

    # Instalar dependencias
    - name: Install dependencies
      run: npm install

    # Construir el proyecto
    - name: Build Vite project
      run: npm run build
